import QtQuick 2.15

QtObject {
    readonly property color background: "#090909"
    readonly property color foreground: "#fbfbfb"
    readonly property color card: "#090909"
    readonly property color cardForeground: "#fbfbfb"
    readonly property color popover: "#090909"
    readonly property color popoverForeground: "#fbfbfb"
    readonly property color primary: "#fbfbfb"
    readonly property color primaryForeground: "#161616"
    readonly property color secondary: "#1a1a1a"
    readonly property color secondaryForeground: "#fbfbfb"
    readonly property color muted: "#171717"
    readonly property color mutedForeground: "#a3a3a3"
    readonly property color accent: "#171717"
    readonly property color accentForeground: "#fbfbfb"
    readonly property color destructive: "#5f2622"
    readonly property color destructiveForeground: "#ea6959"
    readonly property color border: "#2a2a2a"
    readonly property color input: "#171717"
    readonly property color ring: "#565656"
    readonly property color green: "#4ade80"
    readonly property color greenBg: "#14532d"
    readonly property color blue: "#60a5fa"
    readonly property color blueBg: "#1e3a8a"
    readonly property color yellow: "#facc15"
    readonly property color yellowBg: "#713f12"
    readonly property color red: "#f87171"
    readonly property color redBg: "#7f1d1d"
}
